backend:
  name: github
  repo: riano200612-jpg/mariauxi
  branch: main

  base_url: https://mariauxi-oauth.riano200612.workers.dev
  auth_endpoint: auth

media_folder: img/uploads
public_folder: /img/uploads

publish_mode: editorial_workflow

locale: es