backend:
  name: github
  repo: riano200612-jpg/mariauxi
  branch: main
  base_url: https://mariauxi-oauth.riano200612.workers.dev
  auth_endpoint: auth

site_url: https://mariauxi.com
display_url: https://mariauxi.com

media_folder: "img/uploads"
public_folder: "/img/uploads"

publish_mode: editorial_workflow
locale: es

collections:

  - name: "proyectos"
    label: "Proyectos"
    label_singular: "Proyecto"

    folder: "contenido/proyectos"

    create: true
    delete: true

    slug: "{{slug}}"

    fields:

      - label: "Título"
        name: "title"
        widget: "string"

      - label: "Proyecto destacado"
        name: "featured"
        widget: "boolean"
        default: false
        required: false

      - label: "Estado"
        name: "estado"
        widget: "select"
        options:
          - Disponible
          - Preventa
          - En construcción
          - Entregado
          - Vendido

      - label: "Ciudad"
        name: "ciudad"
        widget: "string"

      - label: "Barrio / Sector"
        name: "sector"
        widget: "string"
        required: false

      - label: "Dirección"
        name: "direccion"
        widget: "string"
        required: false

      - label: "Precio desde"
        name: "precio"
        widget: "string"

      - label: "Área"
        name: "area"
        widget: "string"
        required: false

      - label: "Habitaciones"
        name: "habitaciones"
        widget: "number"
        value_type: "int"
        required: false

      - label: "Baños"
        name: "banos"
        widget: "number"
        value_type: "int"
        required: false

      - label: "Parqueaderos"
        name: "parqueaderos"
        widget: "number"
        value_type: "int"
        required: false

      - label: "Mapa Google"
        name: "mapa"
        widget: "string"
        required: false

      - label: "Imagen principal"
        name: "cover"
        widget: "image"

      - label: "Galería"
        name: "gallery"
        widget: "list"
        required: false
        field:
          label: "Imagen"
          name: "image"
          widget: "image"

      - label: "Video"
        name: "video"
        widget: "file"
        required: false

      - label: "Brochure PDF"
        name: "pdf"
        widget: "file"
        required: false

      - label: "Descripción"
        name: "body"
        widget: "markdown"

      - label: "SEO"
        name: "seo"
        widget: "object"
        required: false
        fields:

          - label: "Meta título"
            name: "title"
            widget: "string"
            required: false

          - label: "Meta descripción"
            name: "description"
            widget: "text"
            required: false

          - label: "Palabras clave"
            name: "keywords"
            widget: "string"
            required: false